#!/usr/bin/env bash
# To debug the issue, I would start by checking the Nginx configuration file
# to ensure that it is set up to listen on port 80.
# remove the default and create a symbolic link

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
